# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import qa_pb2 as qa__pb2


class QuaAndAnsStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BuildModel = channel.unary_unary(
        '/qa.QuaAndAns/BuildModel',
        request_serializer=qa__pb2.QARequest.SerializeToString,
        response_deserializer=qa__pb2.QAReply.FromString,
        )
    self.GetTop5 = channel.unary_unary(
        '/qa.QuaAndAns/GetTop5',
        request_serializer=qa__pb2.QARequest2.SerializeToString,
        response_deserializer=qa__pb2.QAReply2.FromString,
        )


class QuaAndAnsServicer(object):
  """The greeting service definition.
  """

  def BuildModel(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTop5(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QuaAndAnsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BuildModel': grpc.unary_unary_rpc_method_handler(
          servicer.BuildModel,
          request_deserializer=qa__pb2.QARequest.FromString,
          response_serializer=qa__pb2.QAReply.SerializeToString,
      ),
      'GetTop5': grpc.unary_unary_rpc_method_handler(
          servicer.GetTop5,
          request_deserializer=qa__pb2.QARequest2.FromString,
          response_serializer=qa__pb2.QAReply2.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'qa.QuaAndAns', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
