# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qa.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qa.proto',
  package='qa',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08qa.proto\x12\x02qa\"\x1d\n\tQARequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"\x17\n\x07QAReply\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\"\x1d\n\nQARequest2\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x19\n\x08QAReply2\x12\r\n\x05index\x18\x01 \x01(\x05\x32\x62\n\tQuaAndAns\x12*\n\nBuildModel\x12\r.qa.QARequest\x1a\x0b.qa.QAReply\"\x00\x12)\n\x07GetTop5\x12\x0e.qa.QARequest2\x1a\x0c.qa.QAReply2\"\x00\x62\x06proto3')
)




_QAREQUEST = _descriptor.Descriptor(
  name='QARequest',
  full_name='qa.QARequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='qa.QARequest.filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_QAREPLY = _descriptor.Descriptor(
  name='QAReply',
  full_name='qa.QAReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isOk', full_name='qa.QAReply.isOk', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=70,
)


_QAREQUEST2 = _descriptor.Descriptor(
  name='QARequest2',
  full_name='qa.QARequest2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='qa.QARequest2.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=101,
)


_QAREPLY2 = _descriptor.Descriptor(
  name='QAReply2',
  full_name='qa.QAReply2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='qa.QAReply2.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['QARequest'] = _QAREQUEST
DESCRIPTOR.message_types_by_name['QAReply'] = _QAREPLY
DESCRIPTOR.message_types_by_name['QARequest2'] = _QAREQUEST2
DESCRIPTOR.message_types_by_name['QAReply2'] = _QAREPLY2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QARequest = _reflection.GeneratedProtocolMessageType('QARequest', (_message.Message,), {
  'DESCRIPTOR' : _QAREQUEST,
  '__module__' : 'qa_pb2'
  # @@protoc_insertion_point(class_scope:qa.QARequest)
  })
_sym_db.RegisterMessage(QARequest)

QAReply = _reflection.GeneratedProtocolMessageType('QAReply', (_message.Message,), {
  'DESCRIPTOR' : _QAREPLY,
  '__module__' : 'qa_pb2'
  # @@protoc_insertion_point(class_scope:qa.QAReply)
  })
_sym_db.RegisterMessage(QAReply)

QARequest2 = _reflection.GeneratedProtocolMessageType('QARequest2', (_message.Message,), {
  'DESCRIPTOR' : _QAREQUEST2,
  '__module__' : 'qa_pb2'
  # @@protoc_insertion_point(class_scope:qa.QARequest2)
  })
_sym_db.RegisterMessage(QARequest2)

QAReply2 = _reflection.GeneratedProtocolMessageType('QAReply2', (_message.Message,), {
  'DESCRIPTOR' : _QAREPLY2,
  '__module__' : 'qa_pb2'
  # @@protoc_insertion_point(class_scope:qa.QAReply2)
  })
_sym_db.RegisterMessage(QAReply2)



_QUAANDANS = _descriptor.ServiceDescriptor(
  name='QuaAndAns',
  full_name='qa.QuaAndAns',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=130,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildModel',
    full_name='qa.QuaAndAns.BuildModel',
    index=0,
    containing_service=None,
    input_type=_QAREQUEST,
    output_type=_QAREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTop5',
    full_name='qa.QuaAndAns.GetTop5',
    index=1,
    containing_service=None,
    input_type=_QAREQUEST2,
    output_type=_QAREPLY2,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUAANDANS)

DESCRIPTOR.services_by_name['QuaAndAns'] = _QUAANDANS

# @@protoc_insertion_point(module_scope)
